export const CANVAS_WIDTH = 1080;
export const CANVAS_HEIGHT = 1350;

export const HERO_WIDTH = CANVAS_WIDTH;
export const HERO_HEIGHT = 1015;
export const CONTENT_LEFT = 88;
export const CONTENT_RIGHT = 88;
export const CONTENT_WIDTH = 904;
export const CONTENT_CENTER_X = CANVAS_WIDTH / 2;

// The Golden Master starts the photo fade at y=574.
export const PHOTO_TRANSITION_START_Y = 574;
// The footer transition runs through the complete hero area.
export const PHOTO_TRANSITION_END_Y = 1015;

export const AMBIENT_CENTER_X = 540;
export const AMBIENT_CENTER_Y = 1250;
export const AMBIENT_RADIUS = 720;
export const WORDMARK_AMBIENT_CENTER_Y = 1253;
export const WORDMARK_AMBIENT_RADIUS = 60;

export const HIGHLIGHT_BADGE_SIZE = 128;
// The Golden Master places the visible lime ring about 76 px in from the canvas edges.
export const HIGHLIGHT_BADGE_TOP = 66;
export const HIGHLIGHT_BADGE_RIGHT = 65;

export const TITLE_X = CONTENT_LEFT;
// Spec uses approximately y=850; the Golden Master cap top is near y=866.
export const TITLE_Y = 853;
export const TITLE_MAX_WIDTH = CONTENT_WIDTH;
export const TITLE_FONT_SIZE = 62;
export const TITLE_LINE_HEIGHT = 1.15;

export const TAG_ROW_X = CONTENT_LEFT;
export const TAG_ROW_Y = 936;
export const TAG_ROW_MAX_WIDTH = CONTENT_WIDTH;
export const TAG_ROW_MAX_COUNT = 4;
export const TAG_CHIP_HEIGHT = 38;
export const TAG_CHIP_GAP = 12;
export const TAG_CHIP_PADDING_X = 16;
export const TAG_ICON_SIZE = 18;
export const TAG_ICON_GAP = 6;

export const NUTRITION_CARD_X = CONTENT_LEFT;
export const NUTRITION_CARD_Y = 1048;
export const NUTRITION_CARD_WIDTH = CONTENT_WIDTH;
export const NUTRITION_CARD_HEIGHT = 144;
export const NUTRITION_FOOTER_TOP_Y = NUTRITION_CARD_Y;
export const NUTRITION_CARD_RADIUS = 24;
export const NUTRITION_CARD_BORDER_WIDTH = 1;
export const NUTRITION_CARD_PADDING_X = 32;
export const NUTRITION_CARD_BOTTOM_Y = NUTRITION_CARD_Y + NUTRITION_CARD_HEIGHT;
export const NUTRITION_CARD_BOTTOM_PADDING = 10;
export const NUTRITION_COLUMN_COUNT = 4;
export const NUTRITION_VALUE_ROW_X = NUTRITION_CARD_X + NUTRITION_CARD_PADDING_X;
export const NUTRITION_VALUE_ROW_WIDTH = NUTRITION_CARD_WIDTH - NUTRITION_CARD_PADDING_X * 2;
export const NUTRITION_VALUE_ROW_HEIGHT = 120;
export const NUTRITION_VALUE_FONT_SIZE = 30;
export const NUTRITION_LABEL_FONT_SIZE = 15;
export const NUTRITION_VALUE_ROW_TOP_Y =
	NUTRITION_CARD_BOTTOM_Y - NUTRITION_CARD_BOTTOM_PADDING - NUTRITION_VALUE_ROW_HEIGHT;
export const NUTRITION_VALUE_ROW_BOTTOM_Y = NUTRITION_VALUE_ROW_TOP_Y + NUTRITION_VALUE_ROW_HEIGHT;
export const NUTRITION_DIVIDER_WIDTH = 1;
export const NUTRITION_DIVIDER_HEIGHT = NUTRITION_VALUE_ROW_HEIGHT;
export const NUTRITION_DIVIDER_X = [330, 540, 750] as const;

export const RECIPE_META_ROW_X = CONTENT_LEFT;
export const RECIPE_META_ROW_TOP_Y = 1204;
export const RECIPE_META_ROW_WIDTH = CONTENT_WIDTH;
export const RECIPE_META_ROW_HEIGHT = 24;
export const RECIPE_META_ICON_SIZE = 20;
export const RECIPE_META_FONT_SIZE = 18;
export const RECIPE_META_LINE_HEIGHT = 24;
export const RECIPE_META_ITEM_GAP = 16;
export const RECIPE_META_ICON_GAP = 8;

export const BARBELL_VIEWBOX_WIDTH = 904;
export const BARBELL_VIEWBOX_HEIGHT = 64;
export const BARBELL_CARD_INSET = 40;
export const BARBELL_SCALE =
	(NUTRITION_CARD_WIDTH - BARBELL_CARD_INSET * 2) / BARBELL_VIEWBOX_WIDTH;
export const BARBELL_X = NUTRITION_CARD_X + BARBELL_CARD_INSET;
export const BARBELL_WIDTH = NUTRITION_CARD_WIDTH - BARBELL_CARD_INSET * 2;
export const BARBELL_HEIGHT = BARBELL_VIEWBOX_HEIGHT * BARBELL_SCALE;
export const BARBELL_VIEWBOX_SHAFT_TOP_OFFSET_Y = 29;
export const BARBELL_VIEWBOX_SHAFT_HEIGHT = 6;
export const BARBELL_SHAFT_TOP_OFFSET_Y =
	BARBELL_VIEWBOX_SHAFT_TOP_OFFSET_Y * BARBELL_SCALE;
export const BARBELL_SHAFT_HEIGHT = BARBELL_VIEWBOX_SHAFT_HEIGHT * BARBELL_SCALE;
export const BARBELL_SHAFT_CENTER_Y = NUTRITION_FOOTER_TOP_Y;
export const BARBELL_SHAFT_TOP_Y = BARBELL_SHAFT_CENTER_Y - BARBELL_SHAFT_HEIGHT / 2;
export const BARBELL_Y = BARBELL_SHAFT_TOP_Y - BARBELL_SHAFT_TOP_OFFSET_Y;

export const PRO_PORTION_CENTER_X = CONTENT_CENTER_X;
export const PRO_PORTION_CENTER_Y = BARBELL_SHAFT_CENTER_Y;
export const PRO_PORTION_FONT_SIZE = 20;
export const PRO_PORTION_WIDTH = 200;
export const PRO_PORTION_HEIGHT = PRO_PORTION_FONT_SIZE + 8;
export const PRO_PORTION_TOP = PRO_PORTION_CENTER_Y - PRO_PORTION_HEIGHT / 2;
export const PRO_PORTION_CARD_BORDER_GAP_LEFT = 466;
export const PRO_PORTION_CARD_BORDER_GAP_RIGHT = 614;

export const WORDMARK_CENTER_X = CONTENT_CENTER_X;
export const WORDMARK_VIEWBOX_WIDTH = 1197.24;
export const WORDMARK_VIEWBOX_HEIGHT = 197.35;
export const WORDMARK_WIDTH = 160;
export const WORDMARK_HEIGHT = WORDMARK_WIDTH * WORDMARK_VIEWBOX_HEIGHT / WORDMARK_VIEWBOX_WIDTH;
export const WORDMARK_Y = 1242;
export const WORDMARK_BOTTOM_CLEARANCE = CANVAS_HEIGHT - WORDMARK_Y - WORDMARK_HEIGHT;

export const COLOR_LIME = "#B9EF12";
export const COLOR_AMBIENT_BASE = "#080D0B";
export const COLOR_PANEL = "#0D1511";
export const COLOR_DIVIDER = "#37463D";
export const COLOR_PRIMARY_TEXT = "#F8F9F8";
export const COLOR_SECONDARY_TEXT = "#B9BFBB";
export const COLOR_WORDMARK_BACKGROUND = "#030604";

export const AMBIENT_STOP_LOCAL = COLOR_WORDMARK_BACKGROUND;
export const AMBIENT_STOP_NEAR = "#060C08";
export const AMBIENT_STOP_BASE = "#080F0B";
export const AMBIENT_STOP_EDGE = "#0D190E";