// Diary types

import type { FoodCategory } from './foodCategory';
import type { HintResult } from './hint';

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack' | 'preworkout' | 'postworkout';
export type MealItemSourceType = 'manual' | 'reusableItem' | 'openFoodFacts' | 'ai' | 'ai-meal-estimate' | 'recipe';

// --- Nutrition value containers ---

export interface NutritionValues {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  /** Davon Zucker (g) — optional, aus Nährwerttabelle */
  sugar?: number;
  /** Davon gesättigte Fettsäuren (g) — optional, aus Nährwerttabelle */
  saturatedFat?: number;
  salt?: number;
}

export interface PortionInfo {
  label: string;          // e.g. "1 slice", "1 cup"
  weightGrams?: number;   // grams per portion (if known)
  nutrition?: NutritionValues; // macros per portion (if known)
}

// Legacy alias — used by MealItem.macros (always complete: fiber required at diary level)
export interface MealItemMacros {
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  fiber: number;
}

export interface MealItem {
  id: string;
  name: string;
  sourceType: MealItemSourceType;
  sourceId?: string;
  quantity: number;
  unit: string;
  macros: MealItemMacros; // snapshot at time of logging
  /** True when macros were estimated by AI and not sourced from a verified product */
  isAiEstimate?: boolean;
  /** Detected sub-components of an ai-meal-estimate entry (e.g. ["Schnitzel", "Pommes", "Mayo"]) */
  aiMealEstimateComponents?: string[];
  /** Detected eating context (e.g. "Imbiss", "Kantine") — influences portion assumptions */
  aiMealEstimateContext?: string;
  /** AI confidence level for the overall meal estimate */
  aiMealEstimateConfidence?: 'high' | 'medium' | 'low';
  /** Plain-language assumptions the AI made when no explicit context was provided */
  aiMealEstimateAssumptions?: string[];
  /** True if a photo was used to improve the estimate */
  aiMealEstimatePhotoUsed?: boolean;
  /** ID of the source recipe when sourceType === 'recipe' */
  recipeId?: string;
  /** Number of portions logged (may be fractional, e.g. 0.5) */
  recipePortions?: number;
  /**
   * Optional food category for hint engine and future analytics.
   * Not required — hints for categories only activate when at least one item has a category.
   */
  category?: FoodCategory;
}

export interface Meal {
  id: string;
  userId: string;
  date: string; // YYYY-MM-DD
  type: MealType;
  name: string;
  items: MealItem[];
  createdAt: string;
}

export interface DaySummary {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export type DayType = 'rest' | 'training';
export type WorkoutType = 'gym' | 'bouldering' | 'running' | 'cycling' | 'other';

/** Persisted per-day metadata document (id: "day:YYYY-MM-DD", _docType: "dayMeta"). */
export interface DayMeta {
  /** Format: "day:{date}", e.g. "day:2026-06-03" */
  id: string;
  userId: string;
  /** ISO date string YYYY-MM-DD */
  date: string;
  dayType: DayType;
  workoutType?: WorkoutType;
  updatedAt: string;
  _docType: 'dayMeta';
}

export interface DiaryDayResponse {
  meals: Meal[];
  summary: DaySummary;
  dayType?: DayType;
  workoutType?: WorkoutType;
  /** Rule-based hint for the day — always present in API response. */
  hint?: HintResult;
}

// --- ReusableItem — extended model with Open Food Facts support ---

export type ReusableItemSourceType = 'manual' | 'openFoodFacts' | 'ai' | 'label-scan';
export type NutritionBasis = 'per100g' | 'perPortion' | 'both';

export interface OFFSourceRef {
  provider: 'openFoodFacts';
  barcode?: string;
  productId?: string;
}

export interface ReusableItem {
  id: string;
  userId: string;
  name: string;
  brand?: string;
  /** Whether nutritionPer100g, portion, or both are available */
  nutritionBasis: NutritionBasis;
  nutritionPer100g?: NutritionValues;
  portion?: PortionInfo;
  /** True when enough data exists for reliable macro calculation */
  isComplete: boolean;
  sourceType: ReusableItemSourceType;
  sourceRef?: OFFSourceRef;
  usageCount: number;
  createdAt: string;
  /** AI confidence score 0.0–1.0; only present when sourceType === 'ai' */
  aiConfidence?: number;
  /** Warnings returned by the AI at estimation time; only present when sourceType === 'ai' */
  aiWarnings?: string[];
  /** Lowercase tokens derived from name+brand (auto-generated on create/update) */
  searchTerms?: string[];
  /** Lowercase keywords generated by the AI enrichment pipeline (separate from searchTerms tokens) */
  aiKeywords?: string[];
  /** True when aiKeywords have been generated by the AI enrichment pipeline */
  searchTermsEnriched?: boolean;
  /**
   * Optional food category for hint engine and future analytics.
   * Not required — populated by AI enrichment or manual user input in future stories.
   */
  category?: FoodCategory;
  /**
   * Blob Storage path of the product image (e.g. "userId/itemId.jpg").
   * Access via GET /api/reusable-items/:id/image which returns a short-lived SAS URL.
   * null = kein Bild vorhanden.
   */
  imageUrl?: string;
}

// --- Food search result (unified view across user library + OFF) ---

export interface FoodSearchResult {
  id: string;
  source: 'library' | 'openFoodFacts';
  name: string;
  brand?: string;
  displayLabel: string; // e.g. "100g · 380 kcal" or "1 serving · 250 kcal"
  nutritionBasis: NutritionBasis;
  nutritionPer100g?: NutritionValues;
  portion?: PortionInfo;
  isComplete: boolean;
  sourceRef?: OFFSourceRef;
  category?: FoodCategory;
  /** True when this result came from an AI-estimated ReusableItem */
  isAiEstimate?: boolean;
  /** AI confidence 0.0–1.0; only present when isAiEstimate === true */
  aiConfidence?: number;
  /** True when the current user has marked this product as favorite */
  isFavorite?: boolean;
  /** Front image URL (from Open Food Facts or Blob Storage for personal products) */
  imageUrl?: string;
}

// --- AI Food Estimate — response shape for POST /api/ai/food-estimate/preview ---

export interface AiFoodEstimateNutrition {
  per: '100g';
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  salt?: number;
}

export interface AiFoodEstimatePortion {
  label: string;
  weightGrams: number;
  /** How many of these single-unit portions the user's input referred to (e.g. 2 for "2 Scheiben"). Defaults to 1 when absent. */
  suggestedAmount?: number;
}

export interface AiFoodEstimatePreview {
  displayName: string;
  estimatedNutritionPer100g: AiFoodEstimateNutrition;
  estimatedPortion: AiFoodEstimatePortion | null;
  category: string | null;
  /** Specific well-known product used as the nutritional reference (e.g. "Golden Toast Vollkorn"). Null if only category averages were used. */
  sourceProduct: string | null;
  /** Lowercase search keywords for improved findability in the user library */
  searchTerms: string[];
  /** 0.0 (very uncertain) – 1.0 (highly confident) */
  confidence: number;
  warnings: string[];
}

// --- Nutrition Label Scan — response shape for POST /api/ai/label-scan ---

export interface NutritionLabelScanNutrition {
  calories: number | null;
  protein: number | null;
  carbs: number | null;
  sugar: number | null;
  fat: number | null;
  saturatedFat: number | null;
  fiber: number | null;
  salt: number | null;
}

export interface NutritionLabelScanServingSize {
  label: string;
  weightGrams: number;
}

export interface NutritionLabelScanResult {
  productName: string | null;
  brand: string | null;
  baseUnit: '100g' | '100ml' | 'serving';
  servingSize: NutritionLabelScanServingSize | null;
  nutrition: NutritionLabelScanNutrition;
  ocrConfidence: number;
  aiConfidence: number;
  warnings: string[];
  rawOcrText: string;
}

