// Diary types

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';
export type MealItemSourceType = 'manual' | 'reusableItem' | 'openFoodFacts' | 'ai';

// --- Nutrition value containers ---

export interface NutritionValues {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
}

export interface PortionInfo {
  label: string;          // e.g. "1 slice", "1 cup"
  weightGrams?: number;   // grams per portion (if known)
  nutrition?: NutritionValues; // macros per portion (if known)
}

// Legacy alias — used by MealItem.macros (always complete: fiber required at diary level)
export interface MealItemMacros {
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
  fiber: number;
}

export interface MealItem {
  id: string;
  name: string;
  sourceType: MealItemSourceType;
  sourceId?: string;
  quantity: number;
  unit: string;
  macros: MealItemMacros; // snapshot at time of logging
  /** True when macros were estimated by AI and not sourced from a verified product */
  isAiEstimate?: boolean;
}

export interface Meal {
  id: string;
  userId: string;
  date: string; // YYYY-MM-DD
  type: MealType;
  name: string;
  items: MealItem[];
  createdAt: string;
}

export interface DaySummary {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

export interface DiaryDayResponse {
  meals: Meal[];
  summary: DaySummary;
}

// --- ReusableItem — extended model with Open Food Facts support ---

export type ReusableItemSourceType = 'manual' | 'openFoodFacts' | 'ai' | 'label-scan';
export type NutritionBasis = 'per100g' | 'perPortion' | 'both';

export interface OFFSourceRef {
  provider: 'openFoodFacts';
  barcode?: string;
  productId?: string;
}

export interface ReusableItem {
  id: string;
  userId: string;
  name: string;
  brand?: string;
  /** Whether nutritionPer100g, portion, or both are available */
  nutritionBasis: NutritionBasis;
  nutritionPer100g?: NutritionValues;
  portion?: PortionInfo;
  /** True when enough data exists for reliable macro calculation */
  isComplete: boolean;
  sourceType: ReusableItemSourceType;
  sourceRef?: OFFSourceRef;
  usageCount: number;
  createdAt: string;
  /** AI confidence score 0.0–1.0; only present when sourceType === 'ai' */
  aiConfidence?: number;
  /** Warnings returned by the AI at estimation time; only present when sourceType === 'ai' */
  aiWarnings?: string[];
  /** Lowercase search keywords generated by AI to improve discoverability (e.g. ["toast", "vollkorn", "brot"]) */
  searchTerms?: string[];
}

// --- Food search result (unified view across user library + OFF) ---

export interface FoodSearchResult {
  id: string;
  source: 'library' | 'openFoodFacts';
  name: string;
  brand?: string;
  displayLabel: string; // e.g. "100g · 380 kcal" or "1 serving · 250 kcal"
  nutritionBasis: NutritionBasis;
  nutritionPer100g?: NutritionValues;
  portion?: PortionInfo;
  isComplete: boolean;
  sourceRef?: OFFSourceRef;
  /** True when this result came from an AI-estimated ReusableItem */
  isAiEstimate?: boolean;
  /** AI confidence 0.0–1.0; only present when isAiEstimate === true */
  aiConfidence?: number;
}

// --- AI Food Estimate — response shape for POST /api/ai/food-estimate/preview ---

export interface AiFoodEstimateNutrition {
  per: '100g';
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  salt?: number;
}

export interface AiFoodEstimatePortion {
  label: string;
  weightGrams: number;
  /** How many of these single-unit portions the user's input referred to (e.g. 2 for "2 Scheiben"). Defaults to 1 when absent. */
  suggestedAmount?: number;
}

export interface AiFoodEstimatePreview {
  displayName: string;
  estimatedNutritionPer100g: AiFoodEstimateNutrition;
  estimatedPortion: AiFoodEstimatePortion | null;
  category: string | null;
  /** Specific well-known product used as the nutritional reference (e.g. "Golden Toast Vollkorn"). Null if only category averages were used. */
  sourceProduct: string | null;
  /** Lowercase search keywords for improved findability in the user library */
  searchTerms: string[];
  /** 0.0 (very uncertain) – 1.0 (highly confident) */
  confidence: number;
  warnings: string[];
}

// --- Nutrition Label Scan — response shape for POST /api/ai/label-scan ---

export interface NutritionLabelScanNutrition {
  calories: number | null;
  protein: number | null;
  carbs: number | null;
  sugar: number | null;
  fat: number | null;
  saturatedFat: number | null;
  fiber: number | null;
  salt: number | null;
}

export interface NutritionLabelScanServingSize {
  label: string;
  weightGrams: number;
}

export interface NutritionLabelScanResult {
  productName: string | null;
  brand: string | null;
  baseUnit: '100g' | '100ml' | 'serving';
  servingSize: NutritionLabelScanServingSize | null;
  nutrition: NutritionLabelScanNutrition;
  ocrConfidence: number;
  aiConfidence: number;
  warnings: string[];
  rawOcrText: string;
}

