// Recipe types

// ---------------------------------------------------------------------------
// Nutrition (aligned with nutritionCalculator.ts — no G suffix)
// ---------------------------------------------------------------------------

export interface RecipeNutrition {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

// ---------------------------------------------------------------------------
// Ingredient
// ---------------------------------------------------------------------------

export type RecipeIngredientInputMode = 'grams' | 'portion';

export interface RecipeIngredient {
  id: string;
  /** Human-readable name (may include brand/product qualifier) */
  displayName: string;
  inputMode: RecipeIngredientInputMode;
  /** Amount as entered by the user (grams or portions) */
  inputAmount: number;
  /** Resolved gram weight for nutrition calculation */
  amountGrams: number;
  /** Display unit label (e.g. "g", "Scheibe", "Portion") */
  unit: string;
  /** Link to food catalog product (null if custom/AI) */
  linkedProductId: string | null;
  /** Link to user's reusable item library (null if catalog/AI) */
  linkedReusableItemId: string | null;
  /** True when nutrition was estimated by AI */
  isAiEstimate: boolean;
  /** Nutrition per 100g — used to recalculate on edit */
  nutritionPer100g: RecipeNutrition;
  /** Pre-calculated contribution of this ingredient to the total recipe */
  nutritionContribution: RecipeNutrition;
}

// ---------------------------------------------------------------------------
// Step
// ---------------------------------------------------------------------------

export interface RecipeStep {
  /** 1-based ordering index */
  order: number;
  title?: string;
  description: string;
  notes?: string;
}

// ---------------------------------------------------------------------------
// Image
// ---------------------------------------------------------------------------

export interface RecipeImage {
  id: string;
  /** Blob path: {userId}/{recipeId}/{imageId}.{ext} — stored in Cosmos */
  blobName: string;
  /** 1-based display order */
  order: number;
  /**
   * Transient read-only SAS URL (1h TTL).
   * Generated by backend on GET /recipes/:id — never persisted in Cosmos.
   */
  url?: string;
}

// ---------------------------------------------------------------------------
// Recipe
// ---------------------------------------------------------------------------

export type RecipeVisibility = 'private';

export interface Recipe {
  id: string;
  ownerUserId: string;
  name: string;
  description?: string;
  /** Number of portions this recipe yields */
  portions: number;
  ingredients: RecipeIngredient[];
  steps: RecipeStep[];
  images: RecipeImage[];
  /** Aggregate nutrition for the full recipe */
  nutritionTotal: RecipeNutrition;
  /** Nutrition per single portion (= nutritionTotal / portions) */
  nutritionPerPortion: RecipeNutrition;
  /** Always 'private' for now — architecture ready for future sharing */
  visibility: RecipeVisibility;
  /** Future sharing — user IDs explicitly granted access */
  sharedWithUserIds: string[];
  tags: string[];
  /** ISO timestamp of last diary log — used for "Zuletzt verwendet" sorting */
  lastUsedAt?: string;
  /** Total number of times this recipe was logged into the diary */
  usageCount: number;
  createdAt: string;
  updatedAt: string;
}
