export const DAILY_INSIGHT_ACTIVITY_MODULE = `## Schwerpunkt besondere Aktivität
Die Aktivität ist ein eigener Kontext und darf nicht automatisch als reguläres Training umgedeutet werden.

- Bei activityCompletionStatus "planned" ist die Aktivität eingetragen oder geplant. Verwende Formulierungen wie "Die Tour ist geplant" oder "Für später steht die Tour an". Schreibe nicht "absolviert", "abgeschlossen", "durchgeführt" oder "Du hast die Tour gemacht".
- Bei "likely_completed" ist eine Durchführung nur wahrscheinlich. Verwende zwingend ein Unsicherheitswort oder eine Bedingung, zum Beispiel "Die Tour hat wahrscheinlich stattgefunden" oder "Wenn die Tour bereits stattgefunden hat". Eine Formulierung wie "wahrscheinlich abgeschlossen" bleibt als probabilistische Aussage zulässig, darf aber niemals als sichere Tatsache erscheinen.
- Bei "unknown" bleibt der Abschluss neutral. Sage zum Beispiel "Die Aktivität ist eingetragen, aber ihr Abschluss lässt sich nicht beurteilen". Behaupte keine Durchführung und schreibe nicht "Du hast die Tour gemacht".
- Verwende nur vorhandene Signale wie Typ, Dauer, Strecke, Höhenmeter, Gelände und Gepäck. Erfinde keine fehlenden Werte.
- Wenn mehrere vorhandene Signale wie mehrstündige Bewegungszeit, lange Strecke, deutliche Höhenmeter, alpines Gelände oder mittlere beziehungsweise schwere Gepäcklast auf eine lange oder intensive Ausdauerbelastung hindeuten, behandle sie qualitativ als solchen Fall. Leite dafür keine neue numerische Schwelle ab.
- In diesem Fall ist ein expliziter Fueling-Hinweis verpflichtend und darf nicht durch einen bloßen Flüssigkeits- oder Regenerationshinweis ersetzt werden: Nenne im Zusammenhang mit der Belastung mindestens einmal "Kohlenhydrate" oder "Energie" als Teil der weiteren Versorgung. Bei "planned" und "unknown" muss dieser Hinweis passend konditional bleiben.
- Ergänze im selben Output außerdem einen Hinweis auf Flüssigkeit sowie Regeneration oder Erholung. Alle drei Aspekte müssen vorkommen; ein allgemeiner Satz über den Kalorienbonus allein genügt nicht.
- Wenn nutrition.targets oder ein positives/negatives remainingCalories vorhanden ist, ordne die Aktivität zusätzlich am vorhandenen Tagesziel oder Energiebedarf ein. Nenne dafür einen natürlichen Begriff wie "Tagesziel", "Kalorienziel" oder "Energiebedarf"; der Fueling-Hinweis und die Regeneration ersetzen diese Einordnung nicht.
- Berücksichtige das erhöhte effektive Kalorienziel, wenn es im nutrition-Kontext vorhanden ist. Hohe absolute Kalorien sind bei einem höheren Ziel nicht automatisch problematisch.
- Wenn ein aktuelles effektives Aktivitätsziel mit Grundziel und Aktivitätsbonus vorliegt, muss mindestens in title oder summary eine natürliche Zielvokabel wie "Kalorienziel", "Tagesziel", "Energiebedarf" oder eindeutig bezogen "Ziel" vorkommen. Eine Aktivitätsbeschreibung ohne diese Einordnung ist unvollständig.
- Wenn remainingProteinG kleiner oder gleich 20 ist, ist das Proteinziel nahezu erreicht. Empfehle dann weder zusätzliches Protein noch eine weitere Mahlzeit oder einen Snack. Eine recommendation oder ein CTA darf in diesem Lock-Fall nur einen nicht-ernährungsbezogenen Hinweis zu Aktivität, Flüssigkeit oder Erholung enthalten.
- Erwähne technische Berechnungsfelder und den Aktivitätsstatus nicht wörtlich.`;