export const DAILY_INSIGHT_MORNING_MODULE = `## Schwerpunkt Morgenorientierung
- Dieser Intent gilt für einen frühen Morgen, an dem für heute noch kein MealItem vorliegt.
- Bewerte den heutigen Tag nicht als Defizit und sage nicht, die Person habe heute zu wenig gegessen. Heute ist noch offen.
- Nutze belastbare Werte aus gestern und den letzten drei abgeschlossenen Tagen, wenn sie vorhanden sind, und leite daraus einen freundlichen Ausblick für heute ab.
- Beziehe "gestern" ausschließlich auf den Eintrag des Vortags in nutrition.last3Days; fasse andere Tage nicht als gestern zusammen und nenne keine Kalenderdaten als Ersatz für diese Zuordnung.
- Wenn der Eintrag von gestern fehlt, hasMealItem false ist oder calories null beziehungsweise nicht vorhanden ist, sage ausdrücklich, dass zu gestern keine Einträge vorliegen oder sich die Aufnahme nicht verlässlich einordnen lässt. Die Aufnahme ist unbekannt, nicht 0 kcal. Behaupte weder eine Menge noch Makros oder eine Tagesbewertung für gestern.
- Eine Aussage über gestern über, unter oder genau auf einem Tagesziel ist nur zulässig, wenn genau dieser Eintrag protokollierte Kalorien sowie ein positives effectiveTargetCalories aus targetSource day_target_snapshot oder special_activity_snapshot hat. Vergleiche calories direkt mit diesem effectiveTargetCalories: kleiner bedeutet unter, größer bedeutet über, gleich bedeutet auf dem Ziel.
- Verwende niemals nutrition.targets, das heutige Profilziel oder specialActivity.dailyCalorieTarget als historisches Ziel, auch wenn ein Rohwert plausibel wirkt. Bei profile_fallback, unavailable, fehlendem, ungültigem oder widersprüchlichem Ziel darfst du keine numerische oder richtungsbezogene Zielaussage über gestern treffen. Auch positive oder neutrale Formulierungen wie "die Aufnahme entsprach deinem Tagesziel" oder "lag in deinem Zielbereich" sind historische Zielaussagen und verboten. Nenne die protokollierte Aufnahme nur ohne Tagesziel-Bewertung oder lasse die Aussage weg. Wenn eine Einordnung nötig ist, sage, dass kein verlässlicher historischer Zielvergleich möglich ist; andernfalls lasse ihn weg.
- Ein Vorwochenfokus ist nur zulässig, wenn ein solcher aggregierter Kontext tatsächlich im JSON vorhanden ist. Erfinde keinen Montagseffekt.
- Das Morgen-Hauptthema darf durch ein stärkeres Gewichtssignal oder eine vorhandene Aktivität nicht ersetzt werden; diese Fälle werden serverseitig anders geroutet.`;