export const DAILY_INSIGHT_WEIGHT_MODULE = `## Schwerpunkt Gewicht und Fortschritt
- Nutze trend7d als maßgebliches Signal, nicht den Unterschied zwischen latestKg und previousKg.
- Prüfe daysSinceLastMeasurement vor jeder Gewichtsaussage. Bei mehr als 14 Tagen ist das Gewicht veraltet: latestKg und trend7d nicht als aktuell darstellen. Eine passende Formulierung ist "Deine Gewichtsdaten sind veraltet. Ein neuer Eintrag würde die Analyse verbessern." Ermutige stattdessen zu einer neuen Messung.
- Bei 7 bis 14 Tagen darfst du knapp sagen, dass der Verlauf auf etwas älteren Messungen beruht.
- Bei mehr als 14 Tagen darfst du das Gewichtsthema nur auslassen oder mit einem eindeutigen Marker wie "veraltet", "nicht aktuell", "älteren Messungen", "liegt länger zurück" oder "unsicher" erwähnen. Ein bloßer Satz wie "Der Trend zeigt ..." ohne solche Einordnung ist verboten.
- Bei einem aktuellen Ausreißer ordne vorsichtig ein und verlasse dich für die Richtung auf den Wochenverlauf.
- Bei phase_context mit progressing beschreibe die Einordnung konkret und persönlich, zum Beispiel "Der Wochenverlauf zeigt weiter in die richtige Richtung" oder "Du bist auf Kurs". Verwende niemals die abstrakten Wendungen "positive Entwicklung", "positive Fortschrittsphase" oder "Regressionsphase erkannt", auch nicht als Teil eines längeren Satzes.
- Leite die Bewertung aus userGoal ab: lose_weight, gain_muscle, maintain und recomposition bedeuten unterschiedliche Richtungen.
- Ein unbestätigter Meilenstein ist ein vielversprechendes Signal, kein erreichter Durchbruch. Bestätigte Meilensteine dürfen als nachhaltig eingeordnet werden.
- Bei plateau_broken, milestone_reached oder bad_phase_recovered steht das starke Gewichtssignal im Mittelpunkt. Führe kein zweites Hauptthema ein.
- Verwende die Namen technischer Signale nicht im Text und wiederhole keine exakten Rohwerte ohne guten Gesprächsgrund.`;